Set-Content -Encoding UTF8 .\.pre-commit-config.yaml @"
default_language_version:
  python: python

repos:
  - repo: local
    hooks:
      - id: black-run
        name: black
        stages: [pre-commit]
        language: system
        entry: python -m black .
        pass_filenames: false
        always_run: true

      - id: pytest-check
        name: pytest-check
        stages: [pre-push]
        language: system
        entry: python -m pytest -q
        pass_filenames: false
        always_run: true
"@
